# Generated by Django 3.1.12 on 2021-07-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NovelViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewsNovelName', models.SlugField(default=10)),
                ('views', models.IntegerField(default=0)),
                ('weeklyViews', models.IntegerField(default=0)),
                ('monthlyViews', models.IntegerField(default=0)),
                ('yearlyViews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('linkNU', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('numOfChaps', models.IntegerField(default=0)),
                ('numOfTranslatedChaps', models.IntegerField(default=0)),
                ('novelStatus', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.author')),
                ('category', models.ManyToManyField(to='novels.Category')),
                ('viewsNovelName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='novels.novelviews')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, default=None)),
                ('text', models.TextField()),
                ('title', models.TextField(max_length=100)),
                ('nextChap', models.BooleanField(default=False)),
                ('novSlugChapSlug', models.CharField(blank=True, default=None, max_length=100)),
                ('novelParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='chapter')),
            ],
        ),
    ]
