# Generated by Django 3.1.7 on 2021-03-31 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('linkNU', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('numOfChaps', models.IntegerField(default=0)),
                ('novelStatus', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.author')),
                ('category', models.ManyToManyField(to='novels.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, default=None)),
                ('text', models.TextField()),
                ('title', models.TextField(max_length=100)),
                ('nextChap', models.BooleanField(default=False)),
                ('novSlugChapSlug', models.CharField(blank=True, default=None, max_length=100)),
                ('novelParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='chapter')),
            ],
        ),
    ]
