# Generated by Django 3.1.7 on 2021-03-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
