# Generated by Django 3.1.12 on 2021-07-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20210726_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelviews',
            name='viewsNovelName',
            field=models.SlugField(default=''),
        ),
    ]
