# Generated by Django 3.1.12 on 2021-07-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20210726_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='scrapeLink',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
