# Generated by Django 3.1.12 on 2021-07-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_novel_scrapelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelviews',
            name='viewsNovelName',
            field=models.SlugField(default='', unique=True),
        ),
    ]
