# Generated by Django 3.1.12 on 2021-08-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_remove_chapter_nextchap'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='repeatScrape',
            field=models.BooleanField(default=True),
        ),
    ]
