# Generated by Django 3.1.12 on 2021-08-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_novel_repeatscrape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.ManyToManyField(null=True, to='novels.Category'),
        ),
    ]
