# Generated by Django 3.1.12 on 2021-08-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_auto_20210821_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.ManyToManyField(blank=True, to='novels.Category'),
        ),
    ]
