# Generated by Django 3.1.12 on 2021-08-22 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_auto_20210821_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
