# Generated by Django 3.1.12 on 2021-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0011_chapter_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='novelRef',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
