# Generated by Django 3.1.12 on 2021-09-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_novel_novelref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='viewsNovelName',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novelviews'),
        ),
    ]
