# Generated by Django 3.1.12 on 2021-09-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0013_auto_20210910_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='scrapeLink',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
