# Generated by Django 3.1.12 on 2021-09-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0016_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, to='novels.Tag'),
        ),
    ]
