# Generated by Django 3.1.12 on 2021-09-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0019_auto_20210918_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
