# Generated by Django 3.1.12 on 2021-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0020_auto_20210918_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='sources',
            field=models.CharField(choices=[('WuxSite', 'WuxSite'), ('ReadNovelFull', 'Sophomore'), ('NovelFull', 'Junior'), ('WuxiaCo', 'WuxiaCo'), ('VipNovel', 'VipNovel')], default='WuxSite', max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='repeatScrape',
            field=models.BooleanField(default=False),
        ),
    ]
