# Generated by Django 3.1.12 on 2021-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0021_auto_20210924_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='sources',
            field=models.CharField(choices=[('WuxSite', 'WuxSite'), ('ReadNovelFull', 'ReadNovelFull'), ('NovelFull', 'NovelFull'), ('WuxiaCo', 'WuxiaCo'), ('VipNovel', 'VipNovel')], default='WuxSite', max_length=100),
        ),
    ]
