# Generated by Django 3.1.12 on 2021-09-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0023_bookmark_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
