# Generated by Django 3.1.12 on 2021-09-28 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0024_auto_20210926_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
