# Generated by Django 3.1.12 on 2021-09-28 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0025_novel_dateadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='last_read_novel',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
