# Generated by Django 3.1.12 on 2021-09-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0026_auto_20210928_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reading_lists',
            field=models.ManyToManyField(blank=True, to='novels.Chapter'),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
