# Generated by Django 3.1.12 on 2021-09-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0027_auto_20210929_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reading_lists',
            field=models.ManyToManyField(null=True, to='novels.Chapter'),
        ),
    ]
