# Generated by Django 3.1.12 on 2021-10-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0029_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reading_lists',
            field=models.ManyToManyField(null=True, to='novels.Bookmark'),
        ),
    ]
