# Generated by Django 3.1.12 on 2021-10-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0030_auto_20211005_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reading_lists',
            field=models.ManyToManyField(blank=True, null=True, to='novels.Bookmark'),
        ),
    ]
