# Generated by Django 3.1.12 on 2021-10-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0032_auto_20211007_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='novels.settings'),
        ),
    ]
