# Generated by Django 3.1.12 on 2021-10-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0034_auto_20211019_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
