# Generated by Django 3.1.12 on 2021-10-28 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0036_auto_20211021_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistPattersn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
