# Generated by Django 3.1.12 on 2021-10-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0037_blacklistpattersn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlacklistPattersn',
            new_name='BlacklistPattern',
        ),
    ]
