# Generated by Django 3.1.12 on 2021-10-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0038_auto_20211028_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistpattern',
            name='replacement',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
