# Generated by Django 3.1.12 on 2021-10-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0039_blacklistpattern_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistpattern',
            name='pattern',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blacklistpattern',
            name='replacement',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
