# Generated by Django 3.1.12 on 2021-11-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0042_auto_20211118_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='viewsNovelName',
            new_name='views',
        ),
    ]
