# Generated by Django 3.1.12 on 2021-11-23 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0043_auto_20211123_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='last_chap_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 18, 39, 0, 537514, tzinfo=utc)),
        ),
    ]
