# Generated by Django 3.1.12 on 2021-11-23 20:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0044_novel_last_chap_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='last_chap_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 20, 38, 13, 712342, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='N/A', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_read_chapter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='novels.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
