# Generated by Django 3.1.12 on 2021-11-23 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0045_auto_20211123_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='last_chap_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reading_lists',
            field=models.ManyToManyField(blank=True, to='novels.Bookmark'),
        ),
    ]
