# Generated by Django 3.1.12 on 2021-11-25 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0049_auto_20211125_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
