# Generated by Django 3.1.12 on 2021-12-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0051_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_by_user',
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.profile'),
        ),
    ]
