# Generated by Django 3.1.12 on 2021-12-07 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0052_auto_20211202_0801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
        migrations.AddField(
            model_name='report',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.chapter'),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_read_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='novels.chapter'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reported_by', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('novel', 'owner_user')},
        ),
    ]
