# Generated by Django 3.1.12 on 2021-12-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0054_auto_20211210_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='original_image',
            field=models.ImageField(default="", upload_to='original/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novel',
            name='new_image',
            field=models.ImageField(upload_to='full/'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='new_image_thumb',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
