# Generated by Django 3.1.12 on 2021-12-12 01:22

from django.db import migrations, models
import wuxiaworld.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0057_auto_20211212_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='new_image',
            field=models.ImageField(blank=True, null=True, storage=wuxiaworld.custom_storages.FullStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='novel',
            name='new_image_thumb',
            field=models.ImageField(blank=True, null=True, storage=wuxiaworld.custom_storages.ThumbnailStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='novel',
            name='original_image',
            field=models.ImageField(blank=True, null=True, storage=wuxiaworld.custom_storages.OriginalStorage(), upload_to=''),
        ),
    ]
