# Generated by Django 3.1.12 on 2022-01-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0060_auto_20211215_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
