# Generated by Django 3.1.12 on 2022-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0061_auto_20220107_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='autoBookMark',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fontSize',
            field=models.IntegerField(default=20),
        ),
    ]
