# Generated by Django 3.1.12 on 2021-11-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0041_auto_20211118_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('disabled', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('base_url', models.CharField(max_length=200)),
                ('source_novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
