# Generated by Django 3.1.12 on 2021-11-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0042_auto_20211118_1052'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_novel', to='novels.novel'),
        ),
    ]
